version: "2"

services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
      - frontend
      - data-service
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  db:
    restart: always
    image: postgres:12.3
    ports:
      - "5000:5432"
    volumes:
      - ./init_db_data.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres

  rabbitmq:
    image: rabbitmq:3.8.3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  data-service:
    restart: always
    image: tomassukenik/react-app:hateoas-service-0.1.1
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - MSG_BROKER_HOST=rabbitmq
      - MSG_QUEUE_NAME=heroDetailQueue
  frontend:
    restart: always
    image: tomassukenik/react-app:frontend-1.3.0
    depends_on:
      - data-service
